# Generated by Django 2.2.5 on 2019-09-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('rms', models.FloatField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('headshot_p', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('esea_game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_start_time', models.DateTimeField()),
                ('match_end_time', models.DateTimeField()),
                ('injestion_date', models.DateTimeField()),
                ('player_1_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1a', to='esea_scraper.UserGame')),
                ('player_1_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1b', to='esea_scraper.UserGame')),
                ('player_2_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2a', to='esea_scraper.UserGame')),
                ('player_2_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2b', to='esea_scraper.UserGame')),
                ('player_3_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p3a', to='esea_scraper.UserGame')),
                ('player_3_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p3b', to='esea_scraper.UserGame')),
                ('player_4_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p4a', to='esea_scraper.UserGame')),
                ('player_4_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p4b', to='esea_scraper.UserGame')),
                ('player_5_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p5a', to='esea_scraper.UserGame')),
                ('player_5_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p5b', to='esea_scraper.UserGame')),
            ],
        ),
    ]
